/* Independent Camera Physics panel. Sensor/model/renderer are replaceable boundaries. */
var CameraPhysicsPanel=(function(){
  'use strict';
  function escape(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function mount(root,adapters){var tracker=CameraPhysicsCore.createTracker(),selected=null,tracks=[],hands=[],analysis=null,session=null,tick=0,active=false,disposed=false,lastFrame=0,lastStatus='',options={scenario:'auto',stationary:false,mass:null,angle:25};
    root.innerHTML='<div class="cp-layout"><section class="cp-work"><div class="cp-bar"><span class="studio-eyebrow">CAMERA PHYSICS <small>EXPERIMENTAL</small></span><span class="cp-indicator" id="cp-camera-state">Camera off</span></div>'+
      '<div class="cp-viewport"><video id="cp-video" autoplay muted playsinline aria-label="Live camera, processed on this device"></video><canvas id="cp-overlay" aria-label="Tracked objects and candidate force vectors"></canvas><div class="cp-empty" id="cp-empty"><span class="cp-focus-mark" aria-hidden="true">＋</span><h2>Hold something.<br>Question the forces.</h2><p>A book, a bottle, your phone.<br>Explore a physical model of what the camera sees.</p><span class="cp-empty-note">REAL CAMERA INPUT · NO UPLOADS</span></div><span class="cp-stage-note">2D MODEL · SYMBOLIC ARROWS</span></div>'+
      '<div class="cp-controls"><button class="studio-primary" id="cp-start">Start camera analysis <span aria-hidden="true">↗</span></button><button class="studio-button" id="cp-stop" disabled>Stop camera</button><span id="cp-performance">Models load on demand</span></div><p class="cp-status" role="status" id="cp-status">Camera off. Nothing is recorded.</p>'+
      '<div class="cp-object-strip" id="cp-objects" aria-label="Detected objects"><span>Detected objects will appear here.</span></div><details class="cp-privacy"><summary>What this camera can—and cannot—tell you</summary><p>Video stays in this browser. Starting analysis downloads MediaPipe Hands and TensorFlow COCO-SSD models from their public hosts. No frames are recorded or sent to Entelloq or an AI service.</p><p>Only supported object classes are recognized. Boxes are not segmentation masks. Depth, object orientation, mass, friction and actual contact forces are not measured. Hand proximity in the image is not proof of contact. Use a level, stationary camera; model axes assume screen-down gravity.</p><p>Try a book, phone, bottle, cup, ball or remote in good light. If it is not recognized, adjust the view or use another object—there is no fabricated fallback detection.</p></details></section>'+
      '<aside class="cp-inspector" aria-label="Physics analysis"><div class="cp-inspector-head"><span class="studio-eyebrow">SCENE INSPECTOR</span><h2 id="cp-object-name">Waiting for an object</h2><p id="cp-model-title">Your camera has not started.</p></div><dl class="cp-facts"><div><dt>Mass</dt><dd id="cp-mass-fact">Unknown</dd></div><div><dt>Orientation / depth</dt><dd>Not estimated</dd></div><div><dt>Physical contact</dt><dd id="cp-contact-fact">Not established</dd></div></dl>'+
      '<div class="cp-model-inputs"><label for="cp-scenario">Physical model <span>assumption, not detection</span></label><select id="cp-scenario"><option value="auto">Suggest from hand proximity</option><option value="held">Held in a hand</option><option value="table">Resting on a level table</option><option value="push">Pushed to the right on a table</option><option value="string">Hanging from a vertical string</option><option value="incline">On an inclined surface</option></select><label class="cp-check"><input id="cp-equilibrium" type="checkbox"> Assume translational equilibrium</label><div class="cp-input-pair"><label for="cp-mass">Known mass <span>optional · kg</span><input id="cp-mass" type="number" min="0.001" max="1000" step="any" placeholder="Unknown" inputmode="decimal"></label><label for="cp-angle" id="cp-angle-label" hidden>Surface angle <span>your input · °</span><input id="cp-angle" type="number" min="0" max="75" value="25" step="1"></label></div></div>'+
      '<section class="cp-analysis"><h3>Candidate forces</h3><div id="cp-forces"><p>Select a detected object to begin.</p></div><h3>Equations for this model</h3><div id="cp-equations"><p>No scene model yet.</p></div><details open><summary>Observed · inferred · assumed</summary><div id="cp-evidence"><p>Evidence will appear with a tracked object.</p></div></details></section></aside></div>';
    function $(s){return root.querySelector(s);}var video=$('#cp-video'),canvas=$('#cp-overlay');
    function status(text){if(text!==lastStatus){$('#cp-status').textContent=text;lastStatus=text;}}
    function clear(){tracker.reset();tracks=[];hands=[];selected=null;analysis=null;lastFrame=0;render();}
    function sensorState(state,message){if(disposed)return;active=['permission','loading','running'].indexOf(state)>=0;$('#cp-start').disabled=active;$('#cp-stop').disabled=!active;$('#cp-start').textContent=state==='error'?'Retry camera analysis':'Start camera analysis ↗';$('#cp-camera-state').textContent={off:'Camera off',permission:'Awaiting permission',loading:'Loading models',running:'Camera live',error:'Camera unavailable'}[state]||state;root.dataset.cameraState=state;$('#cp-empty').hidden=state==='loading'||state==='running';status(message);if(!active){clear();clearInterval(tick);tick=0;$('#cp-performance').textContent='Models load on demand';}else if(!tick)tick=setInterval(expire,180);}
    function resetOptions(){options={scenario:'auto',stationary:false,mass:null,angle:25};$('#cp-scenario').value='auto';$('#cp-equilibrium').checked=false;$('#cp-mass').value='';$('#cp-angle').value='25';$('#cp-angle-label').hidden=true;}
    function select(id){if(selected!==id){selected=id;resetOptions();}render();}
    function expire(){if(!active)return;var now=performance.now(),current=tracker.current(now);if(current.length!==tracks.length||lastFrame&&now-lastFrame>700){tracks=current;hands=[];render();if(lastFrame&&now-lastFrame>700)status('Tracking lost. Bring the object fully back into view.');}}
    function onFrame(frame){if(disposed||!active)return;var delayed=performance.now()-frame.time>700;lastFrame=delayed?0:frame.time;hands=delayed?[]:frame.hands;tracker.update(frame.objects,frame.hands,frame.time);tracks=tracker.current(performance.now());root.querySelector('.cp-viewport').style.aspectRatio=frame.width+' / '+frame.height;
      if(!tracks.some(function(t){return t.id===selected;})){var next=tracks.slice().sort(function(a,b){return Number(!!b.contact)-Number(!!a.contact)||b.score-a.score;})[0];selected=next?next.id:null;resetOptions();}
      $('#cp-performance').textContent='Analysis '+Math.round(frame.latency)+' ms · on device';$('#cp-performance').dataset.samples=frame.samples;status(delayed?'Analysis is too slow for a live overlay on this device. Close other apps or try Hands / Build. Delayed results are hidden.':tracks.length?'Object tracked. Select it, then inspect the candidate model and assumptions.':'Looking for a supported object. Keep it fully visible in good light.');render();}
    function render(){var chosen=tracks.find(function(t){return t.id===selected;});analysis=chosen?CameraPhysicsCore.interpret(chosen,options):null;$('#cp-object-name').textContent=chosen?chosen.object_class:'Waiting for an object';$('#cp-model-title').textContent=analysis?analysis.title:'No object tracked. No force diagram is being inferred.';$('#cp-mass-fact').textContent=options.mass!==null&&analysis?options.mass+' kg · entered':'Unknown';$('#cp-contact-fact').textContent=chosen&&chosen.contact?'2D proximity only':'Not established';
      var objects=$('#cp-objects'),focus=document.activeElement,focusedId=focus&&focus.dataset&&focus.dataset.objectId;
      objects.innerHTML=tracks.length?tracks.map(function(t){return '<button class="studio-button" data-object-id="'+t.id+'" aria-pressed="'+(t.id===selected)+'">'+escape(t.object_class)+' <span>'+Math.round(t.score*100)+'%</span></button>';}).join(''):'<span>Detected objects will appear here.</span>';
      if(focusedId){var next=objects.querySelector('[data-object-id="'+focusedId+'"]');if(next)next.focus({preventScroll:true});}
      $('#cp-forces').innerHTML=analysis?analysis.forces.map(function(f){return '<div class="cp-force"><b>'+escape(f.label)+'</b><span>'+ (f.newtons===null?'Magnitude unknown':f.newtons.toFixed(2)+' N · model-derived')+'</span></div>';}).join(''):'<p>Select a detected object to begin.</p>';
      $('#cp-equations').innerHTML=analysis?analysis.equations.map(function(e){return '<p class="cp-equation">'+escape(e)+'</p>';}).join(''):'<p>No scene model yet.</p>';
      $('#cp-evidence').innerHTML=analysis?[['Observed',analysis.facts],['Inferred',analysis.inferences.length?analysis.inferences:['No physical contact established.']],['Assumed',analysis.assumptions]].map(function(group){return '<h4>'+group[0]+'</h4><ul>'+group[1].map(function(s){return '<li>'+escape(s)+'</li>';}).join('')+'</ul>';}).join(''):'<p>Evidence will appear with a tracked object.</p>';
      CameraPhysicsRendering.paint(canvas,tracks,hands,selected,analysis);
    }
    session=CameraPhysicsVision.createSession(video,{state:sensorState,frame:onFrame},adapters);
    $('#cp-start').onclick=function(){session.start();};$('#cp-stop').onclick=function(){session.stop();};
    $('#cp-objects').onclick=function(e){var b=e.target.closest('[data-object-id]');if(b)select(+b.dataset.objectId);};
    canvas.onclick=function(e){var r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;var t=tracks.find(function(t){var b=t.bbox;return x>=1-b[0]-b[2]&&x<=1-b[0]&&y>=b[1]&&y<=b[1]+b[3];});if(t)select(t.id);};
    function inputs(){options.scenario=$('#cp-scenario').value;options.stationary=$('#cp-equilibrium').checked;var m=$('#cp-mass'),v=m.value===''?null:Number(m.value);options.mass=m.validity.valid&&v>0&&v<=1000?v:null;var angle=Number($('#cp-angle').value);options.angle=Number.isFinite(angle)?Math.max(0,Math.min(75,angle)):25;$('#cp-angle-label').hidden=options.scenario!=='incline';render();}
    ['#cp-scenario','#cp-equilibrium','#cp-mass','#cp-angle'].forEach(function(s){$(s).addEventListener('input',inputs);});
    function hidden(){if(document.hidden&&session.isActive())session.stop('Camera stopped while this tab was hidden. Start again when ready.');}
    document.addEventListener('visibilitychange',hidden);var observer=new ResizeObserver(function(){CameraPhysicsRendering.paint(canvas,tracks,hands,selected,analysis);});observer.observe(canvas);
    return {stop:function(){session.stop();},dispose:function(){session.stop();disposed=true;observer.disconnect();document.removeEventListener('visibilitychange',hidden);clearInterval(tick);},state:function(){return {active:active,tracks:tracks,analysis:analysis};}};
  }
  return {mount:mount};
})();
