const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.join(__dirname,'..'),source=fs.readFileSync(path.join(root,'experience/welcome-tour.js'),'utf8');
function fixture(initial=null,reduced=false){
 const storage=new Map(),nodes=new Map(),callbacks=[],timeouts=new Map(),routes=[];let current=initial,time=0,tick=null,id=0;
 const doc={hidden:false,activeElement:null,addEventListener(){},body:{appendChild(n){nodes.set('#'+n.id,n);}},querySelector:s=>node(s)};
 function node(s){if(s==='#lab-full.on')return null;if(!nodes.has(s)){const attrs={},events={},classes=new Set();nodes.set(s,{open:false,isConnected:true,style:{},textContent:'',value:0,disabled:false,innerHTML:'',classList:{contains:k=>classes.has(k),toggle(k,v){v?classes.add(k):classes.delete(k);}},setAttribute:(k,v)=>attrs[k]=v,getAttribute:k=>attrs[k],addEventListener:(k,f)=>events[k]=f,fire:(k,e={})=>events[k]?.(e),focus(){doc.activeElement=this},click(){events.click?.()},showModal(){this.open=true},close(){this.open=false;events.close?.()},getBoundingClientRect:()=>({left:250,top:150,right:550,bottom:250,width:300,height:100})});}return nodes.get(s);}
 const context={localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},document:doc,window:{addEventListener(){}},innerWidth:1440,innerHeight:1000,performance:{now:()=>time},matchMedia:()=>({matches:reduced}),$:node,ce:()=>node('created-'+(++id)),main:{querySelector:()=>node('h1')},go:v=>routes.push(v),AppDesign:{icon:()=>''},Landing:{pending:()=>false,visible:()=>false},GAuth:{user:()=>current,onChange:f=>callbacks.push(f)},setTimeout:f=>{const k=++id;timeouts.set(k,f);return k;},clearTimeout:k=>timeouts.delete(k),setInterval:f=>{tick=f;return 1;},clearInterval:()=>{tick=null;},Date};
 vm.createContext(context);vm.runInContext(source,context);
 return {context,storage,node,routes,signIn(u){current=u;callbacks.forEach(f=>f(u));const q=[...timeouts.values()];timeouts.clear();q.forEach(f=>f());},flush(){const q=[...timeouts.values()];timeouts.clear();q.forEach(f=>f());},advance(ms){time+=ms;tick?.();}};
}
const ada={n:'Ada',e:'ada@example.invalid'},max={n:'Max',e:'max@example.invalid'};
test('Original founder portrait is unchanged and embedded for standalone HTML',()=>{const image=fs.readFileSync(path.join(root,'assets/darsh-prasad.jpg'));assert.equal(crypto.createHash('sha256').update(image).digest('hex'),'f30b43e4e3f72223f4ae9d043e22c0cc8218ea2c014451c9bd0c1022a44f4e90');const html=fs.readFileSync(path.join(root,'index.html'),'utf8');assert.ok(html.includes('data:image/jpeg;base64,'+image.toString('base64')));assert.equal((html.match(/id="pe-founder"/g)||[]).length,1);assert.ok(html.includes('I built Entelloq so students could finally play it.'));});
test('First successful identity callback starts an automatic eight-step tour',()=>{const f=fixture();f.context.WelcomeTour.init();f.signIn(ada);assert.equal(f.node('#welcome-tour').open,true);assert.equal(f.node('#welcome-play').getAttribute('aria-pressed'),'true');assert.equal(f.routes[0],'home');f.advance(11200);assert.equal(f.routes.at(-1),'universe');assert.equal(f.context.WelcomeState.read(ada).step,1);});
test('Skip is remembered; another account still gets its own welcome',()=>{const f=fixture();f.context.WelcomeTour.init();f.signIn(ada);f.node('#welcome-skip').click();assert.equal(f.context.WelcomeState.read(ada).status,'skipped');f.signIn(null);f.signIn(ada);assert.equal(f.node('#welcome-tour').open,false);f.signIn(max);assert.equal(f.node('#welcome-tour').open,true);});
test('Complete, replay, pause and back preserve the intended state',()=>{const f=fixture();f.context.WelcomeTour.init();f.signIn(ada);f.node('#welcome-next').click();assert.equal(f.node('#welcome-play').getAttribute('aria-pressed'),'false');f.advance(20000);assert.equal(f.context.WelcomeState.read(ada).step,1);f.node('#welcome-back').click();assert.equal(f.context.WelcomeState.read(ada).step,0);for(let i=0;i<8;i++)f.node('#welcome-next').click();assert.equal(f.context.WelcomeState.read(ada).status,'completed');f.context.WelcomeTour.start(ada,true);assert.equal(f.context.WelcomeState.read(ada).step,0);assert.equal(f.node('#welcome-tour').open,true);});
test('Existing signed-in users are not interrupted and guests are not auto-enrolled',()=>{const f=fixture(ada);f.context.WelcomeTour.init();f.flush();assert.equal(f.context.WelcomeState.read(ada).status,'existing');assert.equal(f.routes.length,0);const g=fixture();g.context.WelcomeTour.init();g.flush();assert.equal(g.routes.length,0);});
test('Reduced motion starts at the learner pace; an interrupted tour resumes',()=>{const f=fixture(null,true);f.context.WelcomeTour.init();f.signIn(ada);assert.equal(f.node('#welcome-play').getAttribute('aria-pressed'),'false');f.advance(20000);assert.equal(f.context.WelcomeState.read(ada).step,0);const g=fixture(ada);g.context.WelcomeState.write(ada,'active',3);g.context.WelcomeTour.init();g.flush();assert.equal(g.routes[0],'lab');});
test('Blocked or corrupt storage has a safe in-memory fallback',()=>{const f=fixture();f.storage.set(f.context.WelcomeState.key(ada),'{broken');assert.equal(f.context.WelcomeState.shouldStart(ada),true);f.storage.set(f.context.WelcomeState.key(ada),JSON.stringify({v:1,status:'active',step:'bad'}));assert.equal(f.context.WelcomeState.read(ada).step,0);f.context.localStorage.getItem=()=>{throw Error('blocked')};f.context.localStorage.setItem=()=>{throw Error('blocked')};f.context.WelcomeState.write(ada,'skipped',2);assert.equal(f.context.WelcomeState.shouldStart(ada),false);assert.equal(f.context.WelcomeState.shouldStart(max),true);});
test('Uninterrupted auto-play completes all eight steps and stops its clock',()=>{const f=fixture();f.context.WelcomeTour.init();f.signIn(ada);for(let i=0;i<8;i++)f.advance(11200);assert.equal(f.node('#welcome-tour').open,false);assert.equal(f.context.WelcomeState.read(ada).status,'completed');const count=f.routes.length;f.advance(30000);assert.equal(f.routes.length,count);});
test('Signing out closes the welcome and stops its clock; active account switching restarts safely',()=>{const f=fixture();f.context.WelcomeTour.init();f.signIn(ada);f.signIn(max);assert.equal(f.context.WelcomeState.read(max).step,0);assert.equal(f.node('#welcome-tour').open,true);f.signIn(null);assert.equal(f.node('#welcome-tour').open,false);const count=f.routes.length;f.advance(30000);assert.equal(f.routes.length,count);});
