const{test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),search=fs.readFileSync(path.join(root,'experience/search.js'),'utf8');
function compile(s){const sandbox={window:{}};vm.createContext(sandbox);vm.runInContext(html.slice(html.indexOf('var Grapher=(function(){'),html.indexOf('var LabVig=(function(){')),sandbox);return sandbox.window.__peqGx.compile(s);}
test('Grapher rejects malformed and non-finite numeric literals',()=>{for(const s of['1..2','1.2.3','.','1e309'])assert.ok(compile(s).err,s);});
test('Scientific notation has its numeric meaning, not Euler multiplication',()=>{assert.equal(compile('1e-3').fn(0,{}),.001);assert.equal(compile('2.5E+2*x').fn(2,{}),500);});
test('Existing graph arithmetic, implicit multiplication and precedence remain intact',()=>{for(const[s,x,p,value]of[['-x^2',3,{},-9],['2x+1',4,{},9],['a*x^2+b',3,{a:2,b:1},19],['2^3^2',0,{},512],['2e',0,{},2*Math.E],['sin(pi/2)',0,{},1]])assert.ok(Math.abs(compile(s).fn(x,p)-value)<1e-9,s);});
test('Malformed search-history storage safely falls back to a usable list',()=>{const f=search.match(/function recents\(\)\{[\s\S]*?\n  \}/)[0];for(const raw of['{}','null','3','"oops"','[null,3,{}, {"k":"lesson","id":"energy"}]','{broken']){const result=vm.runInNewContext(f+'; recents()', {RKEY:'x',localStorage:{getItem:()=>raw}});assert.ok(Array.isArray(result));assert.ok(result.every(r=>r&&typeof r.id==='string'));}});
test('Search has one shortcut handler, native modal focus, and real listbox options',()=>{assert.equal((html.match(/document\.addEventListener\('keydown',function\(e\)\{if\(\(e.ctrlKey\|\|e.metaKey\)/g)||[]).length,1);assert.ok(search.includes("el=ce('dialog')"));for(const s of['role="combobox"','role="option"','aria-activedescendant','aria-selected','#feature-guide:popover-open'])assert.ok(search.includes(s),s);assert.ok(!html.includes('this.blur(); Pal.open();'));});
test('Every lab mode disposes of old simulation views and graph observers',()=>{const f=html.match(/function stopLabViews\(\)\{[^\n]*\}/)[0],calls=[];const ctx={stopThumbs:()=>calls.push('thumbs')};for(const k of['Research','Theory','Investigate','DesignLab','CompareDeck','Grapher','LabVig'])ctx[k]={stop:()=>calls.push(k)};vm.runInNewContext(f+';stopLabViews()',ctx);assert.equal(calls.length,8);assert.ok(html.includes('stopSim(); stopLabViews(); setCrumb'));assert.ok(html.includes('if(observer){observer.disconnect();observer=null;}'));});
