/* A readable field atlas, built from the existing concept and prerequisite data. */
var FieldCatalogue=(function(){
  var descriptions={mechanics:'The language of motion, force and balance.',waves:'How energy travels, overlaps and resonates.',thermo:'Heat, probability and the direction of change.',optics:'Light as a ray, a wave and an instrument.',electrostatics:'Charges, fields and the energy between them.',current:'Moving charge. Circuits that do useful work.',magnetism:'Fields that turn motion into electricity.',modern:'Where classical intuition meets its limits.',quantum:'States, probabilities and the structure of matter.',relativity:'Space, time and gravity at their extremes.'};
  var drawings={mechanics:'M25 87Q70 5 119 55T215 80M25 96H215M45 85V68m0 0-5 6m5-6 5 6',waves:'M10 60Q25 5 40 60T70 60T100 60T130 60T160 60T190 60T220 60M10 60H230',thermo:'M20 95H224M25 93Q55 92 80 38T128 47Q162 84 218 92M73 95V75m36 20V47m36 48V68',optics:'M95 90 130 20l35 70ZM15 30 114 52l88 0M141 52l68-30m-65 31 66-14m-63 16 68-3',electrostatics:'M85 58a26 26 0 1 0-52 0 26 26 0 0 0 52 0M207 58a26 26 0 1 0-52 0 26 26 0 0 0 52 0M50 58h18m-9-9v18m113-9h18M89 36Q120 16 151 36M89 80Q120 100 151 80M90 58h59',current:'M25 60V25h75l4-7 8 14 8-14 8 14 8-14 4 7h75v70H140m-40 0H25V60M100 83v24m10-17v10m10-17v24m10-17v10',magnetism:'M50 35v34a30 30 0 0 0 60 0V35h-18v34a12 12 0 0 1-24 0V35ZM141 24q70 32 0 64m10-51q39 22 0 36',modern:'M30 86h180M55 72h130M75 51h90M87 21h67M127 78V30m0 0-5 7m5-7 5 7',quantum:'M15 64H225M20 64q22-3 35-9T78 78Q103 12 119 64t29 0q18 15 27-6t47 6',relativity:'M25 20Q120 35 215 20M25 43Q120 86 215 43M25 67Q120 113 215 67M25 93Q120 105 215 93M60 15Q75 65 60 100m40-85q15 48 0 85m40-85q-15 48 0 85m40-85q-15 48 0 85'};
  function art(k){return '<svg class="field-art" viewBox="0 0 240 116" fill="none" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+(drawings[k]||drawings.mechanics)+'"/></svg>';}
  function cards(){return DOMAINS.map(function(d,i){var count=topicsOf(d.k).length;return '<button class="field-card" style="--field:'+d.c+'" data-link="domain:'+d.k+'"><span class="field-num">'+String(i+1).padStart(2,'0')+' / '+count+' CONCEPTS</span>'+art(d.k)+'<h2>'+esc(d.n)+'</h2><p>'+descriptions[d.k]+'</p><span class="field-bottom">'+Me.domDone(d.k)+' explored '+AppDesign.icon('arrow')+'</span></button>';}).join('');}
  return {art:art,cards:cards,descriptions:descriptions};
})();
function viewLibrary(){
  setCrumb([{t:'Learn'}]);
  var next=Me.recommend(1)[0];
  main.innerHTML='<div class="wrap pe-catalogue"><div class="pe-page-head"><div><div class="eyebrow">THE PHYSICS LIBRARY</div><h1>Find your way into an idea.</h1><p>Ten fields. '+DB.length+' connected concepts. Start with a question, then follow it as far as it takes you.</p></div><span class="pe-index-mark" aria-hidden="true">∑</span></div>'+(next?'<button class="pe-reading-next" data-link="lesson:'+next.id+'"><span class="eyebrow">A PLACE TO BEGIN</span><strong>'+esc(next.name)+'</strong><span>'+esc(DMAP[next.domain].n)+'</span>'+AppDesign.icon('arrow')+'</button>':'')+'<div class="pe-field-grid">'+FieldCatalogue.cards()+'</div><div class="pe-library-foot"><span>Want a more structured path?</span><button class="btn" data-go="journeys">Learning journeys →</button><button class="btn" data-go="deeps">Full courses →</button></div></div>';
}
var Atlas=(function(){
  var field=null,selected=null,filter='all',query='',mode=matchMedia('(max-width:850px)').matches?'outline':'map';
  function mount(){
    var rec=Me.recommend(1)[0];
    main.innerHTML='<div class="wrap pe-atlas"><div class="pe-page-head"><div><div class="eyebrow">THE PHYSICS UNIVERSE</div><h1>Everything is connected.</h1><p>Choose a field. Meet its ideas. See what they build on—and where they lead.</p></div><div class="atlas-view" aria-label="Atlas view"><button data-atlas-mode="map" aria-pressed="'+(mode==='map')+'">Spatial</button><button data-atlas-mode="outline" aria-pressed="'+(mode==='outline')+'">Outline</button></div></div><div class="atlas-tools"><label for="atlas-search">Find a concept<input id="atlas-search" type="search" placeholder="Try energy, waves, gravity…" value="'+esc(query)+'"></label><div class="atlas-filters" aria-label="Concept filter">'+[['all','All ideas'],['ready','Ready next'],['review','Revisit'],['explored','Explored']].map(function(f){return '<button data-atlas-filter="'+f[0]+'" aria-pressed="'+(filter===f[0])+'">'+f[1]+'</button>';}).join('')+'</div></div><div id="atlas-results"></div>'+(rec?'<button class="atlas-next" data-link="lesson:'+rec.id+'"><span>NEXT CONNECTION</span><strong>'+esc(rec.name)+'</strong><small>'+((Graph.readiness(rec.id).missing||[]).length?'Explore its foundations in the atlas.':'Its prerequisite foundations are in place.')+'</small>'+AppDesign.icon('arrow')+'</button>':'')+'</div>';
    $('#atlas-search').addEventListener('input',function(){query=this.value;selected=null;results();});
    $$('[data-atlas-filter]').forEach(function(b){b.addEventListener('click',function(){filter=b.dataset.atlasFilter;selected=null;$$('[data-atlas-filter]').forEach(function(x){x.setAttribute('aria-pressed',String(x===b));});results();});});
    $$('[data-atlas-mode]').forEach(function(b){b.addEventListener('click',function(){mode=b.dataset.atlasMode;field=null;selected=null;mount();});});results();
  }
  function matches(t){if(field&&t.domain!==field)return false;if(query&&!(t.name+' '+t.summary+' '+DMAP[t.domain].n).toLowerCase().includes(query.toLowerCase()))return false;if(filter==='ready')return !Me.isDone(t.id)&&Graph.readiness(t.id).ready;if(filter==='explored')return Me.isDone(t.id);if(filter==='review')return Mastery.queue().some(function(x){return x.id===t.id;});return true;}
  function results(){
    var host=$('#atlas-results');if(!host)return;
    if(!field&&!query&&filter==='all'){
      host.innerHTML='<div class="atlas-fields '+(mode==='map'?'spatial':'outline')+'"><svg class="atlas-lines" viewBox="0 0 1000 400" preserveAspectRatio="none" aria-hidden="true"><path d="M100 100 300 300 500 100 700 300 900 100M100 300 300 100 500 300 700 100 900 300M100 100H900M100 300H900"/></svg><div class="atlas-centre" aria-hidden="true"><span>PHYSICS</span><small>'+DB.length+' IDEAS · ONE UNIVERSE</small></div>'+DOMAINS.map(function(d,i){return '<button class="atlas-field" data-field="'+d.k+'" style="--field:'+d.c+';--ax:'+(10+(i%5)*20)+'%;--ay:'+(i<5?20:80)+'%"><span class="atlas-glyph">'+FieldCatalogue.art(d.k)+'</span><strong>'+esc(d.n)+'</strong><small>'+topicsOf(d.k).length+' concepts</small></button>';}).join('')+'</div><p class="atlas-legend">Colour identifies a field. The overview lines suggest shared ideas, not prerequisites. Select a concept to see its exact connections.</p>';
      $$('[data-field]',host).forEach(function(b){b.addEventListener('click',function(){field=b.dataset.field;selected=null;results();});});return;
    }
    var topics=DB.filter(matches);
    host.innerHTML='<div class="atlas-field-head"><button id="atlas-back">← All fields</button><h2>'+(field?esc(DMAP[field].n):'Concepts')+'</h2><span aria-live="polite">'+topics.length+' '+(topics.length===1?'idea':'ideas')+'</span></div><div class="atlas-detail-grid"><div class="atlas-topics">'+(topics.length?topics.map(function(t){return '<button data-concept="'+t.id+'" aria-pressed="'+(selected===t.id)+'"><span class="atlas-topic-mark" style="color:'+DMAP[t.domain].c+'">'+(Me.isDone(t.id)?'✓':'○')+'</span><span><strong>'+esc(t.name)+'</strong><small>'+esc(DMAP[t.domain].n)+'</small></span>'+AppDesign.icon('arrow')+'</button>';}).join(''):'<div class="pe-empty"><h3>No concepts here yet.</h3><p>'+(filter==='review'?'Your review queue is clear. Explore something new, then return when an idea needs refreshing.':'Try another filter or a shorter search.')+'</p></div>')+'</div><section class="atlas-concept" id="atlas-concept" aria-label="Concept connections"></section></div>';
    $('#atlas-back').addEventListener('click',function(){field=null;selected=null;query='';filter='all';mount();});
    $$('[data-concept]',host).forEach(function(b){b.addEventListener('click',function(){selected=b.dataset.concept;$$('[data-concept]').forEach(function(x){x.setAttribute('aria-pressed',String(x===b));});detail();var h=$('#atlas-concept h2');if(h){h.tabIndex=-1;h.focus({preventScroll:true});if(matchMedia('(max-width:700px)').matches)h.scrollIntoView({block:'start',behavior:'auto'});}});});detail();
  }
  function detail(){
    var host=$('#atlas-concept');if(!host)return;var t=selected?topicById(selected):null;
    if(!t){host.innerHTML='<span class="eyebrow">CHOOSE AN IDEA</span><h2>See the connections.</h2><p>Every concept has a history and a future. Select one to find the foundations it needs and the ideas it unlocks.</p>'+FieldCatalogue.art(field||'mechanics');return;}
    function group(title,ids){return ids.length?'<div class="atlas-links"><h3>'+title+'</h3>'+ids.slice(0,6).map(function(id){var c=topicById(id);return c?'<button data-related="'+id+'">'+esc(c.name)+AppDesign.icon('arrow')+'</button>':'';}).join('')+'</div>':'';}
    var pre=Graph.prereqsOf(t.id),unlocks=Graph.unlocks(t.id),related=Graph.relatedOf(t.id).map(function(r){return r.id;});
    host.innerHTML='<span class="eyebrow">'+esc(DMAP[t.domain].n)+'</span><h2>'+esc(t.name)+'</h2><p>'+esc(t.summary)+'</p><button class="btn btn-pri" data-link="lesson:'+t.id+'">Explore this concept →</button>'+(!pre.length?'<p class="atlas-root-note">A foundational idea. No prerequisites are listed.</p>':'')+group('Understand first',pre)+group('Where this leads',unlocks)+group('Across the fields',related);
    $$('[data-related]',host).forEach(function(b){b.addEventListener('click',function(){selected=b.dataset.related;$$('[data-concept]').forEach(function(x){x.setAttribute('aria-pressed',String(x.dataset.concept===selected));});detail();var h=host.querySelector('h2');h.tabIndex=-1;h.focus({preventScroll:true});});});
  }
  return {mount:mount};
})();
function viewUniverse(){setCrumb([{t:'Universe'}]);Atlas.mount();}
