/* The command centre: a real experiment first; an honest, personal next step later. */
function viewHome(){
  setCrumb([{t:'Home'}]);
  var start=adaptiveStart(),first=!Me.doneCount()&&!Me.d.lastTopic&&start.link!=='review';
  var target=start.link.indexOf('lesson:')===0?topicById(start.link.slice(7)):null;
  var title=first?'A thread of possibility.':target?target.name:'Bring an idea back into focus.';
  var description=first?'Pull a strand. Move a support. Discover how a simple thread distributes a force. No setup needed.':target?target.summary:start.note;
  var art='<svg viewBox="0 0 480 320" aria-hidden="true"><defs><radialGradient id="cc-glow"><stop stop-color="#3b7587" stop-opacity=".24"/><stop offset="1" stop-color="#10232d" stop-opacity="0"/></radialGradient></defs><circle cx="240" cy="150" r="185" fill="url(#cc-glow)" stroke="none"/><path d="M65 65 Q210 135 415 235 Q438 180 415 65 Q260 200 65 235 Q38 140 65 65" stroke-width="1.8"/><path d="M65 65V265 M415 65V265 M45 265H435" stroke-dasharray="2 7" opacity=".25"/><g fill="#e8bd89" stroke="none"><circle cx="65" cy="65" r="5"/><circle cx="415" cy="65" r="5"/><circle cx="415" cy="235" r="5"/><circle cx="65" cy="235" r="5"/></g></svg>';
  main.innerHTML='<div class="wrap cc-home fade"><div class="cc-head"><div><div class="eyebrow">YOUR PHYSICS COMMAND CENTRE</div><h1>Your next discovery.</h1></div><p>Build a model of the world.<br>One experiment at a time.</p></div>'+
    '<section class="cc-hero"><div class="cc-hero-copy"><small>'+(first?'FEATURED EXPERIMENT / CAT’S CRADLE':'YOUR NEXT CONNECTION')+'</small><h2>'+esc(title)+'</h2><p>'+esc(description)+'</p><button class="btn" '+(first?'id="cc-start"':'data-link="'+start.link+'"')+'>'+esc(first?'Start exploring':start.label)+' ↗</button></div><div class="cc-art">'+art+'<span>TENSION · FORCE BALANCE · ELASTIC ENERGY</span></div></section>'+
    '<div class="cc-worlds"><button class="cc-world" data-scene="catcradle"><span class="cc-ic">∾</span><small>01 / THE STRING INSTRUMENT</small><h3>Cat’s Cradle ↗</h3><p>Pull, pluck, predict. Follow force through a weave you can reshape.</p></button><button class="cc-world" data-scene="solar"><span class="cc-ic">◎</span><small>02 / THE ORBITAL PLAYGROUND</small><h3>Make a world ↗</h3><p>Build a solar system. Change a velocity. Find the boundary of an orbit.</p></button><button class="cc-world" data-link="lesson:wave-basics"><span class="cc-ic">∿</span><small>03 / THE WAVES STUDIO</small><h3>Watch energy travel ↗</h3><p>Trace a wave from its motion to the mathematics that describes it.</p></button></div>'+
    '<section class="cc-map"><div class="cc-map-head"><div><small>CONNECTED, NOT COLLECTED</small><h3>Your Physics Map</h3></div><button class="btn btn-sm" data-go="universe">Open the universe ↗</button></div><div class="cc-map-grid">'+DOMAINS.map(function(dm){var done=Me.domDone(dm.k),total=topicsOf(dm.k).length,pct=total?100*done/total:0;return '<button class="cc-node" data-link="domain:'+dm.k+'"><b>'+esc(dm.n)+'</b><span><i style="width:'+pct+'%;background:'+dm.c+'"></i></span><small>'+done+' / '+total+' explored</small></button>';}).join('')+'</div><p class="cc-summary">'+Me.doneCount()+' of '+DB.length+' concepts explored. Exploration is a beginning, not proof of mastery. Your confidence and spaced review help decide what comes next.</p></section>'+
    '<button class="as-promo" data-go="adv"><span aria-hidden="true">δS</span><span><small>BEYOND THE FOUNDATIONS / UPPER-UNDERGRADUATE</small><strong>Advanced Studio</strong><p>Full derivations. Live numerical models. Preview the deeper physics.</p></span><span aria-hidden="true">↗</span></button>'+
    '<div class="cc-return"><button class="btn btn-sm" data-go="progress">Your learning & readiness →</button><button class="btn btn-sm" data-go="research">Explore research →</button><button class="btn btn-sm" id="cc-personalise">Personalise my learning</button></div></div>';
  function scene(id){window.__peqNextPreset=id;go('sandbox');}
  var begin=$('#cc-start');if(begin)begin.addEventListener('click',function(){scene('catcradle');});
  $$('.cc-world[data-scene]').forEach(function(b){b.addEventListener('click',function(){scene(b.dataset.scene);});});
  $('#cc-personalise').addEventListener('click',function(){Onboard.show();});
}
