/* Reference-matched observatory launch: embedded artwork with live accessible UI. */
var Landing=(function(){
  var el=null,cleanup=[],done=null;
  function pending(){try{return /landing/.test(location.search+location.hash)||localStorage.getItem('peq_entered')!=='1';}catch(e){return true;}}
  function button(text,dest,cls){return '<button class="'+(cls||'pe-button')+'" data-enter="'+(dest||'home')+'">'+text+' <span aria-hidden="true">↗</span></button>';}
  function show(callback){
    done=callback;el=document.createElement('div');el.id='lnd';el.className='pe-launch';
    el.setAttribute('aria-label','Physics Entelloq');
    el.innerHTML=`
      ${observatoryMarkup()}
      <section class="pe-statement" id="pe-loop"><div class="pe-kicker">THE WAY IN IS THROUGH CURIOSITY</div><h2>A formula is a beginning.<br><span>Make something happen.</span></h2><div class="pe-loop"><article><b>01</b><h3>Predict.</h3><p>Slower satellite. Tighter rope.<br>What do you think will change?</p></article><article><b>02</b><h3>Experiment.</h3><p>Move a mass. Pull a strand.<br>The system answers immediately.</p></article><article><b>03</b><h3>Look closer.</h3><p>Follow the vectors and measurements.<br>Find the evidence for your idea.</p></article><article><b>04</b><h3>Understand.</h3><p>Connect what you saw to the equation.<br>Then try a different situation.</p></article></div></section>
      <section class="pe-world-section" id="pe-worlds"><div class="pe-section-head"><div><div class="pe-kicker">A FEW DOORS INTO A BIG UNIVERSE</div><h2>Choose your curiosity.</h2></div>${button('Explore the concept universe','universe','pe-text-button')}</div><div class="pe-worlds">
        <button class="pe-world pe-world-rope" data-enter="catcradle"><div class="pe-world-visual"><svg viewBox="0 0 480 280" aria-hidden="true"><path d="M60 65 Q200 110 420 220 Q440 150 420 65 Q250 170 60 220 Q25 140 60 65 M60 65 Q240 285 420 65 M60 220 Q240 -5 420 220"/><circle cx="60" cy="65" r="7"/><circle cx="420" cy="65" r="7"/><circle cx="60" cy="220" r="7"/><circle cx="420" cy="220" r="7"/></svg><span class="pe-world-badge">FEATURED INSTRUMENT</span></div><div class="pe-world-copy"><small>01 / TENSION & TOPOLOGY</small><h3>Cat’s Cradle <span>↗</span></h3><p>One thread. A thousand possibilities. Pull, pluck and watch forces find their way.</p><span class="pe-world-meta">Direct manipulation · live force readings</span></div></button>
        <button class="pe-world pe-world-space" data-enter="sandbox"><div class="pe-world-visual"><svg viewBox="0 0 480 280" aria-hidden="true"><ellipse cx="240" cy="140" rx="185" ry="62" transform="rotate(-30 240 140)"/><ellipse cx="240" cy="140" rx="140" ry="88" transform="rotate(25 240 140)"/><circle class="pe-planet" cx="240" cy="140" r="35"/><circle cx="393" cy="66" r="5"/></svg></div><div class="pe-world-copy"><small>02 / SPACE & GRAVITATION</small><h3>Orbital Playground <span>↗</span></h3><p>Build a solar system. Change a velocity. Discover the thin line between orbit and escape.</p><span class="pe-world-meta">N-body gravity · trails · time controls</span></div></button>
        <button class="pe-world pe-world-waves" data-enter="waves"><div class="pe-world-visual"><svg viewBox="0 0 480 280" aria-hidden="true"><path d="M0 140 Q30 35 60 140 T120 140 T180 140 T240 140 T300 140 T360 140 T420 140 T480 140 M0 140 Q60 240 120 140 T240 140 T360 140 T480 140"/><path d="M0 140H480" opacity=".25"/></svg></div><div class="pe-world-copy"><small>03 / WAVES & RESONANCE</small><h3>Waves Studio <span>↗</span></h3><p>See waves add, cancel and stand still. Hear the question behind every vibration.</p><span class="pe-world-meta">Superposition · motion · intuition</span></div></button>
      </div></section>
      <section class="obs-advanced" id="pe-advanced" aria-labelledby="pe-advanced-title"><div><div class="pe-kicker">BEYOND THE FOUNDATIONS</div><h2 id="pe-advanced-title">For the questions<br><em>that go further.</em></h2><p>Advanced Studio connects Lagrangian mechanics, relativity, electromagnetic waves, quantum mechanics, statistical physics and chaos. Follow the derivations, test a model, and examine what its assumptions leave out.</p><p>Advanced undergraduate level. Calculus and foundational physics expected; preview freely, then choose whether to enter.</p>${button('Preview Advanced Studio','adv','pe-text-button')}</div><div class="obs-advanced-art" aria-hidden="true"><span>δS = 0</span><small>ONE PRINCIPLE. MANY POSSIBLE PATHS.</small></div></section>
      <section class="pe-tutor-section"><div><div class="pe-kicker">THINK WITH ENTELLOQ</div><h2>“Why did<br><em>that</em> happen?”</h2><p>A good question can change the experiment. Bring your current concept or a summary of the cradle’s measured state to the tutor, and reason through it together.</p>${button('Meet your physics tutor','tutor','pe-text-button')}</div><div class="pe-conversation"><div class="pe-context"><span>∾</span> CAT’S CRADLE / EXPERIMENT CONTEXT</div><div class="pe-question">Why does the support force rise when I pull the anchors apart?</div><div class="pe-answer"><span class="pe-ai-star">✦</span><div>Look at the angle of each strand. As the rope becomes flatter, how much of its tension still points upward?<div class="pe-thought">The vertical components must still support the same weight.</div></div></div><div class="pe-context-foot">Illustrative teaching exchange · live AI answers may vary</div></div></section>
      <section class="pe-science" id="pe-science"><div class="pe-kicker">BEAUTY NEEDS A FOUNDATION</div><h2>The model matters.</h2><div class="pe-science-grid"><article><span>∑</span><h3>Visible assumptions</h3><p>The orbit preview uses Newtonian two-body dynamics. Cat’s cradle uses a planar elastic string. Model limits belong beside the experiment.</p></article><article><span>↔</span><h3>Ideas that connect</h3><p>${DB.length} concepts, interactive lessons, experiments and research tools. Move between ways of thinking without losing the idea.</p></article><article><span>◳</span><h3>Your map, at your pace</h3><p>Explore concepts, rate your confidence, and revisit ideas through spaced review. Progress stays on this device.</p></article></div></section>
      <section class="pe-faq"><h2>Try your first hand-controlled experiment.</h2><p>Follow the path into Sandbox, find the Hands control, and learn how to grab, move and release an object.</p><button class="feature-guide-cta" data-feature-tutorial>Guide me through hand control ↗</button></section><section class="pe-faq"><h2>A few useful answers.</h2><details><summary>Do I need an account or a powerful computer?</summary><p>You can enter as a guest. The launch experiment is a lightweight 2D canvas, and the core simulations run in your browser. Advanced experiments and hand tracking can need more processing power.</p></details><details><summary>Can I use cat’s cradle without a camera?</summary><p>Yes. Drag the anchors or the rope with a pointer, use the sliders, or pluck a strand with a button. Camera-based hand tracking is optional and only starts when you choose it.</p></details><details><summary>Are these exact models of the real world?</summary><p>No simulation is the whole world. Each model makes assumptions. The cradle is planar, has linear elasticity and damping, and does not simulate true knots, rope failure or friction between crossing strands.</p></details><details><summary>What happens without the AI connection?</summary><p>The experiments, authored lessons and measurements still work. The tutor needs a network connection; its fallback points you to relevant learning material.</p></details></section>
      <section class="pe-founder" id="pe-founder" aria-labelledby="pe-founder-title"><div class="pe-kicker">THE FOUNDER</div><h2 id="pe-founder-title">Built by one student who refused<br>to memorize physics.</h2><div class="pe-founder-story"><figure><img src="__FOUNDER_PORTRAIT__" alt="Darsh Prasad, founder of Entelloq Networks" width="512" height="512" loading="lazy" decoding="async"><figcaption>Darsh Prasad <span>Founder · Designer · Engineer</span></figcaption></figure><div class="pe-founder-copy"><blockquote>“Physics isn’t a wall of formulas — it’s the most beautiful game in the universe. I built Entelloq so students could finally play it.”</blockquote><p>Darsh designed and engineered Physics Entelloq end-to-end — every simulation, every numerical solver, every pixel — on one conviction: the deepest way to understand a law of nature is to run it, bend it, and watch what happens.</p><div class="pe-founder-links"><a href="mailto:entelloqnetworks@gmail.com">Email Darsh ↗</a><a href="https://www.linkedin.com/in/entelloq-networks" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="https://x.com/Entelloqnetwork" target="_blank" rel="noopener noreferrer">X ↗</a><a href="https://www.instagram.com/entelloq/" target="_blank" rel="noopener noreferrer">Instagram ↗</a></div>${button('See what he built','home','pe-text-button')}</div></div></section>
      <section class="pe-final"><div class="pe-kicker">YOUR NEXT DISCOVERY STARTS WITH A SMALL CHANGE</div><h2>The universe is open.<br><em>Go touch it.</em></h2><div class="pe-final-actions"><button class="pe-button pe-primary" data-signup>Create your free account <span aria-hidden="true">↗</span></button>${button('Enter the Physics Lab','home','pe-button')}</div><p class="pe-account-note">An automatic welcome tour after sign-in. Guest exploration stays open.</p></section>
      </main><footer class="pe-footer pe-footer-expanded"><div><span>Physics <b>Entelloq</b></span><p>An Entelloq Networks laboratory.<br>Founded, designed and engineered by Darsh Prasad.</p></div><nav aria-label="Launch page links"><a href="#pe-founder">Meet the founder</a><a href="#pe-science">The science</a><a href="#pe-worlds">The labs</a></nav><nav aria-label="Entelloq company links"><a href="mailto:entelloqnetworks@gmail.com">Get in touch ↗</a><a href="https://www.linkedin.com/in/entelloq-networks" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="https://x.com/Entelloqnetwork" target="_blank" rel="noopener noreferrer">X ↗</a><a href="https://www.instagram.com/entelloq/" target="_blank" rel="noopener noreferrer">Instagram ↗</a></nav></footer>`;
    document.body.appendChild(el);
    document.body.classList.add('pe-landing-open');
    ['.app','.mtab','#tutor-fab','#audio-btn','#eq-pres'].forEach(function(s){var n=document.querySelector(s);if(n){n.inert=true;n.setAttribute('aria-hidden','true');}});
    el.querySelectorAll('[data-enter]').forEach(function(b){b.addEventListener('click',function(){enter(b.dataset.enter);});});
    // Native anchors target the independently scrolling launch surface.
    el.querySelectorAll('a[href^="#pe-"]').forEach(function(a){a.addEventListener('click',function(e){e.preventDefault();var t=el.querySelector(a.getAttribute('href'));if(t){t.scrollIntoView({behavior:'auto'});if(a.classList.contains('pe-skip')){t.setAttribute('tabindex','-1');t.focus({preventScroll:true});}}});});
    orbit();
  }
  function enter(dest){
    if(!el)return;cleanup.forEach(function(f){f();});cleanup=[];
    try{localStorage.setItem('peq_entered','1');}catch(e){}
    el.remove();el=null;document.body.classList.remove('pe-landing-open');
    ['.app','.mtab','#tutor-fab','#audio-btn','#eq-pres'].forEach(function(s){var n=document.querySelector(s);if(n){n.inert=false;n.removeAttribute('aria-hidden');}});
    if(dest==='catcradle'){window.__peqNextPreset='catcradle';go('sandbox');}
    else if(dest==='waves')go('lesson','wave-basics');
    else if(dest==='tutor'){go('home');Tutor.open();}
    else if(dest==='search'){go('home');Cmdk.open();}
    else go(dest||'home');
    var cb=done;done=null;
    // Discover the experiment immediately; onboarding remains available on a later visit.
    if(dest==='home'&&cb)cb();
  }
  function orbit(){cleanup.push(Observatory.mount(el));}
  return {pending:pending,show:show,enter:enter,visible:function(){return !!el;}};
})();
