/* Hand-first workspace composition. Existing simulation, presets and history are
   kept alive while tools are reorganised. Only explicit controls request a camera. */
var SandboxStudio=(function(){
  'use strict';
  var root=null,panel=null,resize=null,hiddenHandler=null,mode='hands';
  var handArt='<svg viewBox="0 0 250 175" aria-hidden="true" class="studio-hand-art"><g fill="none" stroke="currentColor" stroke-width="1.3"><ellipse cx="130" cy="101" rx="95" ry="35" transform="rotate(-19 130 101)" opacity=".2"/><path d="M95 159 78 127 53 106Q42 96 48 90Q52 86 60 92L82 108 64 62Q60 51 66 48Q73 46 77 56L98 99 88 32Q87 21 95 21Q101 21 104 34L117 91 119 20Q120 10 127 13Q133 15 132 27L134 93 151 43Q155 33 162 37Q167 40 163 50L147 110 145 132 157 157"/><path d="m95 159 12-36-25-15m25 15 10-32m-10 32 27-30m-27 30 40-13m-40 13 38 9" opacity=".5"/><circle cx="182" cy="77" r="15"/><path d="m177 72 10 10m0-10-10 10" opacity=".4"/><path d="M154 109 173 89" stroke-dasharray="3 4"/></g><g fill="currentColor">'+[[95,159],[82,108],[64,62],[66,48],[98,99],[88,32],[95,21],[117,91],[127,13],[134,93],[162,37],[147,110],[107,123],[145,132]].map(function(p){return '<circle cx="'+p[0]+'" cy="'+p[1]+'" r="2.5"/>';}).join('')+'</g></svg>';
  function dispose(){if(panel){panel.dispose();panel=null;}if(resize){resize.disconnect();resize=null;}if(hiddenHandler){document.removeEventListener('visibilitychange',hiddenHandler);hiddenHandler=null;}root=null;}
  function mount(host){Sandbox.stop();root=host;host.classList.add('sandbox-studio');
    host.innerHTML='<header class="studio-header"><div><span class="studio-eyebrow">THE PHYSICS SANDBOX</span><h1>Make a move.<br class="studio-mobile-break"> Change the system.</h1></div><p>Hands. Objects. First principles.<br>A space to find out what happens.</p></header>'+
      '<div class="studio-tabs" role="tablist" aria-label="Sandbox workspace"><button id="studio-tab-hands" role="tab" aria-controls="studio-sim-panel" aria-selected="true" data-workspace="hands"><span>01</span> Hands <small>FEEL THE PHYSICS</small></button><button id="studio-tab-camera" role="tab" aria-controls="studio-camera-panel" aria-selected="false" tabindex="-1" data-workspace="camera"><span>02</span> Camera Physics <small>SEE THE FORCES</small></button><button id="studio-tab-build" role="tab" aria-controls="studio-sim-panel" aria-selected="false" tabindex="-1" data-workspace="build"><span>03</span> Build <small>MAKE A WORLD</small></button></div>'+
      '<section id="studio-sim-panel" role="tabpanel" aria-labelledby="studio-tab-hands"><div class="studio-intro"><div><span class="studio-eyebrow" id="studio-mode-label">YOUR HANDS ARE THE CONTROLLER</span><h2 id="studio-mode-title">Reach into the experiment.</h2><p id="studio-mode-copy">Pinch to grab. Open your palm to push. Make a fist to pull.</p></div><div class="studio-quick" aria-label="Quick scenes"><button data-studio-scene="solar">Orbits <span>↗</span></button><button data-studio-scene="catcradle">Cat’s Cradle <span>↗</span></button><button data-studio-scene="dipole">Charges <span>↗</span></button></div></div><div id="studio-simulation"></div></section>'+
      '<section id="studio-camera-panel" role="tabpanel" aria-labelledby="studio-tab-camera" hidden></section>'+
      '<footer class="studio-footer"><span>OBSERVE → CHANGE → EXPLAIN</span><span>Camera is always your choice. Mouse and touch work too.</span></footer>';
    var sim=host.querySelector('#studio-simulation');Sandbox.mount(sim);var grid=sim.querySelector('.sbx');
    var guide=document.createElement('aside');guide.className='studio-hand-guide';guide.setAttribute('aria-label','Hand control guide');guide.innerHTML='<div class="studio-hand-visual">'+handArt+'<span>GESTURE GUIDE · ILLUSTRATION</span></div><h3>Put your hands<br> in the equation.</h3><div id="studio-hand-action"></div><p class="studio-camera-note">On-device hand tracking.<br>Allow your camera when prompted.</p><ol class="studio-gestures"><li><b>01 · Pinch</b><span>Grab a body. Release to let it move.</span></li><li><b>02 · Open palm</b><span>Push nearby bodies away.</span></li><li><b>03 · Close your hand</b><span>Pull nearby bodies toward you.</span></li></ol><p class="studio-cradle-hint" hidden>In Cat’s Cradle, your thumbs and little fingers guide the four rope supports. Keep both hands visible.</p><button class="studio-text-button" id="studio-open-camera">Analyze a real object instead ↗</button>';
    grid.appendChild(guide);var hand=sim.querySelector('#sbx-hand');guide.querySelector('#studio-hand-action').appendChild(hand);hand.textContent='Start hand control ↗';hand.setAttribute('aria-pressed','false');
    var more=document.createElement('details');more.className='studio-more';more.innerHTML='<summary>More controls</summary><div class="studio-more-controls"></div>';var transport=sim.querySelector('.sbx-transport');transport.appendChild(more);['sbx-shot','sbx-share','sbx-sonic','sbx-camreset','sbx-replay','sbx-rwd','sbx-rail-tg','sbx-max-tg'].forEach(function(id){var b=sim.querySelector('#'+id);if(b)more.lastChild.appendChild(b);});
    sim.querySelector('#sbx-play').setAttribute('aria-label','Play or pause simulation');sim.querySelector('#sbx-speed').setAttribute('aria-label','Simulation speed');sim.querySelectorAll('.sbx-tool').forEach(function(b){b.setAttribute('aria-label',b.title);});
    // Legacy group headers become keyboard-operable disclosures without replacing their handlers.
    sim.querySelectorAll('.sbx-rgh').forEach(function(h){h.setAttribute('role','button');h.tabIndex=0;function state(){h.setAttribute('aria-expanded',String(!h.classList.contains('clp')));}h.addEventListener('click',state);h.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();h.click();}});state();});
    var side=sim.querySelector('.sbx-side'),rail=document.createElement('div');rail.className='studio-rail-tabs';rail.setAttribute('role','group');rail.setAttribute('aria-label','Workbench panel');rail.innerHTML=['Scenes','Inspect','Controls'].map(function(t){return '<button data-studio-rail="'+t.toLowerCase()+'" aria-pressed="false">'+t+'</button>';}).join('');
    Array.from(side.children).forEach(function(el){if(el.classList.contains('sbx-rgh'))return;el.dataset.studioGroup=el.classList.contains('rg-lib')?'scenes':el.classList.contains('rg-insp')||el.id==='cr-lab'||el.id==='sbx-probe-card'||el.querySelector('#sbx-chgame')?'inspect':'controls';});side.prepend(rail);
    function chooseRail(name){side.dataset.studioRail=name;side.classList.remove('clp-lib','clp-insp','clp-int');rail.querySelectorAll('button').forEach(function(b){b.setAttribute('aria-pressed',String(b.dataset.studioRail===name));});}
    rail.onclick=function(e){var b=e.target.closest('[data-studio-rail]');if(b)chooseRail(b.dataset.studioRail);};chooseRail('scenes');
    var pie=window.__peqSbx.pie;pie.set('buildMode',false);sim.querySelector('#sbx-pie-buildMode').checked=false;
    function sceneState(){guide.querySelector('.studio-cradle-hint').hidden=!grid.classList.contains('cradle-mode');guide.querySelector('.studio-gestures').hidden=grid.classList.contains('cradle-mode');side.classList.remove('clp-lib','clp-insp','clp-int');var building=sim.querySelector('#sbx-pie-buildMode').checked,items=guide.querySelectorAll('.studio-gestures li span');items[1].textContent=building?'Move up or down to choose an object.':'Push nearby bodies away.';items[2].textContent=building?'Add the chosen object to your scene.':'Pull nearby bodies toward you.';}
    host.querySelectorAll('[data-studio-scene]').forEach(function(b){b.onclick=function(){var target=sim.querySelector('[data-preset="'+b.dataset.studioScene+'"]');if(target)target.click();sceneState();};});
    sim.addEventListener('click',function(){sceneState();});
    function switchMode(next){if(['hands','build','camera'].indexOf(next)<0)return;var prev=mode;mode=next;root.dataset.workspace=next;host.querySelectorAll('[data-workspace]').forEach(function(b){var on=b.dataset.workspace===next;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;});
      host.querySelector('#studio-camera-panel').hidden=next!=='camera';host.querySelector('#studio-sim-panel').hidden=next==='camera';host.querySelector('#studio-sim-panel').setAttribute('aria-labelledby','studio-tab-'+(next==='build'?'build':'hands'));
      if(next==='camera'){Sandbox.suspendView();if(!panel)panel=CameraPhysicsPanel.mount(host.querySelector('#studio-camera-panel'));}
      else {if(panel)panel.stop();if(next==='build')pie.stop();if(prev==='camera')Sandbox.resumeView();host.querySelector('#studio-mode-label').textContent=next==='hands'?'YOUR HANDS ARE THE CONTROLLER':'A WORKBENCH FOR YOUR IDEAS';host.querySelector('#studio-mode-title').textContent=next==='hands'?'Reach into the experiment.':'Create. Change. See what holds.';host.querySelector('#studio-mode-copy').textContent=next==='hands'?'Pinch to grab. Open your palm to push. Make a fist to pull.':'Choose a scene, add a body, then change the forces. The same physics engine, fully in your hands.';window.__peqSbx.draw();}
      if(next==='hands'&&sim.querySelector('#sbx-pie-buildMode').checked){host.querySelector('#studio-mode-copy').textContent='Pinch to grab. Open your palm to choose an object. Make a fist to add it.';}
      guide.hidden=next!=='hands';sceneState();
    }
    host.querySelectorAll('[data-workspace]').forEach(function(b){b.onclick=function(){switchMode(b.dataset.workspace);};b.onkeydown=function(e){var buttons=Array.from(host.querySelectorAll('[data-workspace]')),i=buttons.indexOf(b),next;if(e.key==='ArrowRight')next=(i+1)%3;else if(e.key==='ArrowLeft')next=(i+2)%3;else if(e.key==='Home')next=0;else if(e.key==='End')next=2;if(next!==undefined){e.preventDefault();buttons[next].focus();switchMode(buttons[next].dataset.workspace);}};});
    guide.querySelector('#studio-open-camera').onclick=function(){switchMode('camera');host.querySelector('#studio-tab-camera').focus();};
    hiddenHandler=function(){if(document.hidden)pie.stop();};document.addEventListener('visibilitychange',hiddenHandler);
    resize=new ResizeObserver(function(){if(root&&mode!=='camera')window.__peqSbx.draw();});resize.observe(sim.querySelector('.sbx-stage'));
    switchMode('hands');
    // Minimal state surface for deterministic tests; never fabricates production detections.
    host.__studio={mode:function(){return mode;},camera:function(){return panel&&panel.state();}};
  }
  return {mount:mount,dispose:dispose};
})();
