/* Verify actual computed colours and persistent artwork at the real HTTPS origin. */
const{chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const live=process.argv.includes('--live'),mode=live?'continuity-live':'continuity-staged',out=path.join(__dirname,'results'),report=[];
fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch();try{for(const[device,width,height]of[['reference',1536,1024],['tablet',820,1180],['mobile',390,844],['small',320,740]]){
 const c=await b.newContext({viewport:{width,height},reducedMotion:'reduce'});await c.route(/clarity\.ms|google-analytics/,r=>r.abort());if(!live)await c.route('https://physics.entelloq.com/**',r=>r.request().resourceType()==='document'?r.fulfill({status:200,contentType:'text/html',body:fs.readFileSync(path.join(__dirname,'../index.html'),'utf8')}):r.continue());
 const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('https://physics.entelloq.com/?landing&still&paletteQA='+Date.now(),{waitUntil:'load'});await p.locator('.obs-backdrop img').evaluate(e=>e.decode());
 const plate=await p.locator('.obs-continuum').boundingBox();assert.equal(plate.x,0);assert.equal(plate.y,0);assert.equal(plate.width,width);assert.equal(plate.height,height);
 for(const section of['#pe-loop','#pe-worlds','#pe-advanced','.pe-tutor-section','#pe-science','#pe-founder','.pe-final']){await p.locator(section).scrollIntoViewIfNeeded();assert.deepEqual(await p.locator('.obs-continuum').boundingBox(),plate,'Backdrop stays fixed at '+section);const style=await p.locator(section).evaluate(e=>({background:getComputedStyle(e).backgroundColor,backgroundImage:getComputedStyle(e).backgroundImage}));assert.equal(style.background,'rgba(0, 0, 0, 0)');assert.equal(style.backgroundImage,'none');if(['#pe-loop','#pe-founder'].includes(section))await p.screenshot({path:path.join(out,mode+'-'+device+'-'+section.slice(1)+'.png')});}
 assert.ok(await p.evaluate(()=>getComputedStyle(document.querySelector('.obs-continuum')).backgroundImage.includes(document.querySelector('.obs-backdrop img').src)),'One unchanged artwork is shared');
 await p.locator('.obs-primary').click();assert.equal(await p.locator('.obs-continuum').count(),0);await p.waitForFunction(()=>document.body.dataset.view==='home');
 if(width<=850){const fab=await p.locator('#eqx-fab').boundingBox(),tabs=await p.locator('.mtab').boundingBox();assert.ok(fab.y+fab.height<=tabs.y,'App switcher clears the bottom navigation');}await p.locator('#eqx-fab').click();await p.locator('#eqx-panel.eqx-open').waitFor();await p.keyboard.press('Escape');await p.locator('#eqx-panel').waitFor({state:'hidden'});
 async function palette(){return p.evaluate(()=>{const style=getComputedStyle(document.documentElement);return{bg:style.getPropertyValue('--bg').trim(),accent:style.getPropertyValue('--blue').trim(),app:getComputedStyle(document.querySelector('.app')).backgroundColor};});}
 assert.deepEqual(await palette(),{bg:'#020509',accent:'#9bc3ff',app:'rgb(2, 5, 9)'});assert.match(await p.locator('.cc-art circle').first().getAttribute('fill'),/url\(/,'Keep the soft radial gradient, not a solid circle');await p.screenshot({path:path.join(out,mode+'-'+device+'-app.png')});
 await p.locator('#pe-explore').click();await p.locator('[data-explore-go="settings"]').click();await p.locator('[data-th="light"]').click();assert.deepEqual(await palette(),{bg:'#edf2f8',accent:'#305f96',app:'rgb(237, 242, 248)'});
 await p.goto('https://physics.entelloq.com/?landing&still&paletteQA=light',{waitUntil:'load'});assert.equal(await p.locator('#lnd').evaluate(e=>getComputedStyle(e).color),'rgb(238, 242, 247)','Launch remains photographic dark even with a light workspace');await p.locator('#pe-founder').scrollIntoViewIfNeeded();assert.equal(await p.locator('#pe-founder blockquote').evaluate(e=>getComputedStyle(e).color),'rgb(238, 242, 247)');await p.locator('.obs-primary').click();assert.equal((await palette()).bg,'#edf2f8','Entering the app respects saved light preference');
 await p.locator('#pe-explore').click();await p.locator('[data-explore-go="settings"]').click();await p.locator('[data-th="dark"]').click();await p.goto('https://physics.entelloq.com/?still&paletteQA=cold',{waitUntil:'load'});assert.equal(await p.locator('#lnd').count(),0);assert.equal((await palette()).accent,'#9bc3ff','Returning users get the palette without mounting launch');
 for(const theme of['dark','light']){if(theme==='light'){await p.locator('#pe-explore').click();await p.locator('[data-explore-go="settings"]').click();await p.locator('[data-th="light"]').click();await p.locator((width<=850?'.mtab':'.side')+' [data-go="home"]').click();}await p.locator('[data-scene="catcradle"]').click();await p.locator('.cr-lab').waitFor();await p.addScriptTag({path:require.resolve('axe-core/axe.min.js')});await p.locator('.cr-lab').scrollIntoViewIfNeeded();const a=await p.evaluate(async()=>{const r=await axe.run('.cr-lab',{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});return r.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}));});await p.screenshot({path:path.join(out,mode+'-'+device+'-cradle-'+theme+'.png')});assert.deepEqual(a,[],device+' cradle '+theme);}
 assert.deepEqual(errors,[]);report.push({device,persistentSections:7,coldEntry:true,lightPreference:true,cradleThemes:2,errors});console.log(device,'continuous plate, shared palette, theme preference, cold entry, cradle: passed');await c.close();
}}finally{fs.writeFileSync(path.join(out,mode+'-palette.json'),JSON.stringify(report,null,2));await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
