const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const checks=[];async function check(name,fn){await fn();checks.push(name);console.log('PASS',name);}
(async()=>{const browser=await chromium.launch({headless:true});try{
 const ctx=await browser.newContext({viewport:{width:1280,height:900},reducedMotion:'reduce'}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('https://physics.entelloq.com/?landing&still&edges',{waitUntil:'load'});await page.getByRole('button',{name:'Enter the Physics Lab',exact:true}).first().click();await page.locator('#cc-start').click();await page.locator('#cr-lab').waitFor();
 await check('reduced-motion cradle pauses by default but permits explicit play',async()=>{assert.equal(await page.locator('#cr-stage-pause').innerText(),'Play');await page.locator('#cr-stage-pause').click();const t=await page.evaluate(()=>__peqSbx.simT());await page.waitForTimeout(240);assert.ok(await page.evaluate(()=>__peqSbx.simT())>t);await page.locator('#cr-stage-pause').click();});
 await check('pointer drag moves an anchor and releases the temporary grab',async()=>{
  const p=await page.evaluate(()=>{const st=__peqSbx.state(),b=st.B[st.cradleNodes[0].id],r=document.querySelector('#sbx-c').getBoundingClientRect(),s=__peqSbx.shareState().s;return {x:r.x+r.width/2+b.x*s,y:r.y+r.height/2+10+b.y*s,bx:b.x,id:st.cradleNodes[0].id};});
  await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(p.x+30,p.y+18,{steps:8});await page.mouse.up();const b=await page.evaluate(id=>__peqSbx.state().B[id],p.id);assert.ok(b.x>p.bx+5);assert.equal(b.fixed,true);
 });
 await check('undo restores both the weave and material parameters',async()=>{
  await page.locator('#cr-elasticity').fill('160');await page.locator('#cr-elasticity').dispatchEvent('input');await page.locator('#cr-elasticity').dispatchEvent('change');await page.locator('#sbx-undo').click();assert.equal(await page.locator('#cr-elasticity').inputValue(),'80');
 });
 await check('saved weave survives a full page reload',async()=>{await page.locator('#cr-elasticity').fill('135');await page.locator('#cr-elasticity').dispatchEvent('input');await page.locator('#cr-save').click();await page.goto('https://physics.entelloq.com/?still',{waitUntil:'load'});await page.locator('[data-scene="catcradle"]').click();await page.locator('#cr-restore').click();assert.equal(await page.locator('#cr-elasticity').inputValue(),'135');});
 await check('tutor receives measurements and limitations; provider failure has a useful fallback',async()=>{
  let payload;await page.route('**/*',async route=>{const r=route.request();if(r.method()==='POST'&&r.postData()?.includes('"messages"')){payload=JSON.parse(r.postData());await route.fulfill({status:503,contentType:'application/json',body:'{}'});}else await route.continue();});
  await page.locator('#cr-ask').click();await page.getByText("I can't reach the live AI right now",{exact:false}).waitFor();assert.ok(payload);const content=JSON.stringify(payload.messages);assert.match(content,/peakTensionN/);assert.match(content,/crossing strands/);assert.match(content,/axialStiffnessN/);assert.doesNotMatch(content,/gsk_|Bearer |api[_-]?key/i);await page.locator('#tu-close').click();await page.unroute('**/*');
 });
 await check('loaded cradle works after the network disconnects',async()=>{await ctx.setOffline(true);await page.locator('#cr-span').fill('400');await page.locator('#cr-span').dispatchEvent('input');assert.match(await page.locator('#cr-span-v').innerText(),/4.00/);await page.locator('#cr-pluck').click();await ctx.setOffline(false);});
 await check('leaving the sandbox stops its simulation clock',async()=>{await page.locator('#cr-stage-pause').click();await page.waitForTimeout(120);await page.locator('.nav-i[data-go="home"]').click();await page.locator('.cc-home').waitFor();const t=await page.evaluate(()=>__peqSbx.simT());await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>__peqSbx.simT()),t);});
 assert.deepEqual(errors,[]);await ctx.close();
 const fallback=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});await fallback.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(...args){return this.id==='pe-orbit-canvas'?null:original.apply(this,args);};});const fp=await fallback.newPage();await fallback.route('**/fonts.*',r=>r.abort());await fp.goto('https://physics.entelloq.com/?landing&still&fallback',{waitUntil:'load'});
 await check('unavailable hero canvas exposes a static SVG and usable controls',async()=>{assert.ok(await fp.locator('.pe-orbit-fallback').isVisible());assert.ok(await fp.locator('#pe-pause').isDisabled());await fp.locator('#pe-velocity').fill('1.5');await fp.locator('#pe-velocity').dispatchEvent('input');assert.match(await fp.locator('#pe-orbit-state').innerText(),/ESCAPE/);});await fallback.close();
 const nojs=await browser.newContext({javaScriptEnabled:false}),np=await nojs.newPage();await np.goto('https://physics.entelloq.com/',{waitUntil:'load'});await check('JavaScript-disabled page explains the product and a useful model',async()=>{assert.ok(await np.getByRole('heading',{name:'Understand the universe by changing it.'}).isVisible());assert.ok(await np.getByRole('heading',{name:'One model to start with'}).isVisible());});await nojs.close();
}finally{fs.writeFileSync(path.join(__dirname,'results/edges.json'),JSON.stringify({checks},null,2));await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
