const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true}),results=[];try{for(const [device,width,height] of [['desktop',1440,1000],['mobile',390,844]]){
 const page=await browser.newPage({viewport:{width,height},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{localStorage.setItem('peq_entered','1');localStorage.setItem('peq_onboarded','1');});await page.goto('https://physics.entelloq.com/?still&extendedDesign',{waitUntil:'load'});
 async function shot(name){await page.waitForTimeout(150);const overflow=await page.locator('#main-scroll').evaluate(e=>e.scrollWidth>e.clientWidth+1);await page.screenshot({path:path.join(__dirname,'results','extended-'+device+'-'+name+'.png')});results.push({device,name,overflow});console.log(device,name,'overflow',overflow);}
 for(const route of ['journeys','deeps','adv','sandbox']){await page.locator('#pe-explore').click();await page.locator('[data-explore-go="'+route+'"]').click();if(route==='adv'&&await page.locator('#adv-enter').count()){await page.locator('#adv-enter').click();await page.locator('.av-title').waitFor();}assert.ok((await page.locator('#main').innerText()).length>80);await shot(route);}
 await page.locator((device==='mobile'?'.mtab':'.side')+' [data-go="lab"]').click();
 for(const mode of ['graphs','playground','theory','research','investigate','design','compare','discover','labs']){const button=page.locator('[data-lm="'+mode+'"]');if(!await button.count())continue;await button.click();await shot('lab-'+mode);}
 assert.deepEqual(errors,[]);await page.context().close();
}}finally{await browser.close();fs.writeFileSync(path.join(__dirname,'results/extended-design.json'),JSON.stringify(results,null,2));}if(results.some(r=>r.overflow))process.exitCode=1;})().catch(e=>{console.error(e);process.exitCode=1;});
