/* Broad, isolated HTTPS checks. No camera permission, AI submission or real accounts. */
const{chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path');
const phase=process.argv[2]||'sweep-before',out=path.join(__dirname,'results'),report=[];fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true});try{for(const[device,width,height]of[['desktop',1440,1000],['tablet',768,1024],['small',320,740]]){
 const context=await browser.newContext({viewport:{width,height},reducedMotion:'reduce'});await context.route(/clarity\.ms/,r=>r.abort());await context.addInitScript(()=>{localStorage.setItem('peq_entered','1');localStorage.setItem('peq_onboarded','1');});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('https://physics.entelloq.com/?still&quality='+phase,{waitUntil:'load',timeout:45000});await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});
 async function route(r){await page.locator('#pe-explore').click();const more=page.locator('[data-explore-go="'+r+'"]');if(await more.count())await more.click();else{await page.keyboard.press('Escape');await page.locator((width<=850?'.mtab':'.side')+' [data-go="'+r+'"]').first().click();}}
 async function scan(name,selector='#main'){
  await page.waitForTimeout(100);const data=await page.evaluate(async selector=>{const root=document.querySelector(selector),a=await axe.run(root,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}});const ids=[...root.querySelectorAll('[id]')].map(e=>e.id);return{violations:a.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,html:n.html,summary:n.failureSummary}))})),duplicates:[...new Set(ids.filter((id,i)=>ids.indexOf(id)!==i))],overflow:root.scrollWidth>root.clientWidth+1,unreachable:[...root.querySelectorAll('[onclick],[data-sim],.dom-card,.adv-card')].filter(n=>n.getBoundingClientRect().width&&!n.matches('a,button,input,select,[tabindex]')).map(n=>({tag:n.tagName,cls:n.className,text:n.textContent.slice(0,100)})),wide:[...root.querySelectorAll('*')].filter(e=>{const r=e.getBoundingClientRect(),cs=getComputedStyle(e);return r.width&&r.right>innerWidth+1&&cs.position!=='absolute'&&cs.position!=='fixed'&&!e.closest('.lm-bar,.ln-tabs,.c-tabs,.av-tabs,.lens-tabs')}).slice(0,12).map(n=>({tag:n.tagName,cls:n.className,text:n.textContent.slice(0,50)}))};},selector);
  report.push({device,name,...data});console.log(device,name,JSON.stringify({issues:data.violations.map(v=>v.id+':'+v.nodes.length),duplicates:data.duplicates,overflow:data.overflow,unreachable:data.unreachable.length,wide:data.wide.length}));await page.screenshot({path:path.join(out,phase+'-'+device+'-'+name+'.png')});
 }
 await page.keyboard.press('Control+k');await scan('search',await page.locator('#cmdk.on').count()?'#cmdk':'#pal');report.push({device,name:'search-layer-count',open:await page.locator('#cmdk.on,#pal.on').count()});await page.keyboard.press('Escape');
 for(const r of['journeys','deeps','adv','sandbox']){await route(r);if(r==='adv'&&await page.locator('#adv-enter').count())await page.locator('#adv-enter').click();await scan(r);if(r==='journeys'){await page.locator('#main [data-link^="journey:"]').first().click();await scan('journey');}if(r==='deeps'){await page.locator('#main [data-link^="deep:"]').first().click();await scan('deep');}}
 await route('practice');await page.locator('[data-m="reason"]').click();await page.locator('[data-rid]').first().click();await scan('reason');
 await route('lab');for(const mode of['graphs','theory','research','investigate','design','compare','discover','play','labs']){await page.locator('[data-lm="'+mode+'"]').click();await scan('lab-'+mode);const card=mode==='theory'?'[data-tid]':mode==='research'?'[data-eid]':mode==='investigate'?'[data-nid]':null;if(card){await page.locator(card).first().click();await scan('lab-'+mode+'-open');}}
 await route('settings');await page.locator('[data-th="light"]').click();await route('lab');for(const mode of['graphs','theory','research','investigate','design','compare','discover']){await page.locator('[data-lm="'+mode+'"]').click();await scan('lab-'+mode+'-light');}
 report.push({device,name:'runtime',errors});await context.close();
}}finally{fs.writeFileSync(path.join(out,phase+'.json'),JSON.stringify(report,null,2));await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
